name: Korx.CookieComplier
author: korx
category: Utilities
current: 0.1
tags: [cookie, compliance, law, directive, unobtrusive, accessible]
docs: https://github.com/korx/Korx.CookieComplier/blob/master/README.md
demo: http://korx.github.com/Korx.CookieComplier/Demo/